name: Docker Image

on:
  push:
    paths:
      - ".github/workflows/image.yml"
      - "docker/Dockerfile"
      - "chatbridge/**"
      - "lang/**"
      - "__main__.py"
      - "LICENSE"
      - "mcdreforged.plugin.json"
      - "**/requirements.txt"

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fallenbreath
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            fallenbreath/chatbridge
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: 'linux/amd64'
          file: ./docker/Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
